In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Librairie Numpy

__Cette librairie permet d'utiliser des tableaux (array) (type numpy.ndarray) dont les propriétés sont analogues à celles de vecteurs ou de matrices.__

Contrairement aux listes, les éléments d’un tableau doivent être de même type. Un tableau T peut être unidimensionnel ou multidimensionnel.

In [ ]:
# Import de la librairie numpy
import numpy as np

In [ ]:
# Création d'un numpy array
a=np.array([[ 1, 0, 0],
 [ 0, 1, 2]])
a

array([[1, 0, 0],
       [0, 1, 2]])

In [ ]:
# Accéder à un élément du np array
# Accéder à la deuxième ligne (attention l'indice commence de 0)
print("La deuxième ligne : ", a[1])
# Accéder au premier élement du np array
print("Le premier élément : ", a[0,0])
# ou bien a[0][0]

La deuxième ligne :  [0 1 2]
Le premier élément :  1


In [ ]:
# Dimensions du np array
a.shape

(2, 3)

In [ ]:
# Le nombre de dimension du np array (ici c'est un 2-d array)
a.ndim

2

In [ ]:
# Le nombre total d'élements
a.size

6

In [ ]:
# Créer un numpy 2d-array composé de 0
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# On peut aussi préciser au préalable le type de données
# np.ones((2,3), dtype=complex) 
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Créer une séquence numérique avec arrange()
# np.arange(le_début, la_fin (attention exclus), le_pas)
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# Si le pas est inconnu mais le nombre d'éléments souhaité est connu
# linspace(le_début, la_fin (ici inclus), le_nombre_d'éléments)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Quelques opérations simples possibles sur un np array
# Puissance d'une matrice
a**4
# Somme de matrices
a+a
# La somme des éléments sur un axe donné
a.sum(axis=1)
# Le minimum des éléments sur un axe donné
a.min(axis=0)
# La somme cumulée sur un axe donné
a.cumsum(axis=1)
# D'autres opérations possibles
np.sqrt(a)
np.exp(a)

array([[2.71828183, 1.        , 1.        ],
       [1.        , 2.71828183, 7.3890561 ]])

In [ ]:
# Créeons un autre np array
b=np.array([[3, 5, 7],
           [8, 1, 0]])
print(b)

[[3 5 7]
 [8 1 0]]


In [ ]:
# Itération sur les lignes
for i in b:
    if i.sum(axis=0)>10:
        print(i)
    

[3 5 7]


In [ ]:
# Itération sur les élements 
for j in b.flat:
    if j>5:
        print(j)

7
8


In [ ]:
# Transformer un np array
# Applatir
print("Applati ça donne :\n", b.ravel())
# Transposer
print("Transposé ça donne :\n", b.T)

Applati ça donne :
 [3 5 7 8 1 0]
Transposé ça donne :
 [[3 8]
 [5 1]
 [7 0]]


In [ ]:
# Concaténer deux numpy arrays
# Verticalement
print("Verticalement : \n", np.vstack((a,b)))
# Horizontalement
print("Horizontalement : \n", np.hstack((a,b)))

Verticalement : 
 [[1 0 0]
 [0 1 2]
 [3 5 7]
 [8 1 0]]
Horizontalement : 
 [[1 0 0 3 5 7]
 [0 1 2 8 1 0]]


In [ ]:
# Reshape - Redimensionner un np array
print("Le np array initial :\n ", b)
print("Dimensions initiales : ", b.shape)
print("Le np array redimensionné :\n ", b.reshape((3,2)))
print("Dimensions modifiées : ",b.reshape((3,2)).shape)

### Slicing

In [ ]:
# Créer un numpy array 6*3
import random
a=np.zeros((6,3))

for i in range(6):
  for j in range(3):
    a[i,j]=random.randint(0,18)
a


array([[11.,  4.,  3.],
       [12.,  7., 11.],
       [ 7., 16., 11.],
       [17., 14., 16.],
       [10.,  9., 10.],
       [12., 12.,  3.]])

In [ ]:
# Afficher la ligne 2
a[1,:]
#...............................
#...............................


array([12.,  7., 11.])

In [ ]:
# Afficher toutes les lignes à partir de la lignes 2
a[2:,:]
#...............................
#...............................

array([[ 7., 16., 11.],
       [17., 14., 16.],
       [10.,  9., 10.],
       [12., 12.,  3.]])

In [ ]:
#Afficher toutes les lignes jusqu'à la lignes 4
a[:4,:]
#...............................
#...............................

array([[11.,  4.,  3.],
       [12.,  7., 11.],
       [ 7., 16., 11.],
       [17., 14., 16.]])

In [ ]:
# Afficher la colonne 2
a[:,1]
#...............................
#...............................

array([ 4.,  7., 16., 14.,  9., 12.])

In [ ]:
# Afficher toutes les colonnes à partir de la colonne 2
a[:,2:]
#...............................
#...............................

array([[ 3.],
       [11.],
       [11.],
       [16.],
       [10.],
       [ 3.]])

In [ ]:
a[3:6, 1:3]
# Afficher les colonnes de 2 à 3 pour les lignes entre 4 et 6 
#...............................
#...............................


array([[14., 16.],
       [ 9., 10.],
       [12.,  3.]])